### ISSUE TITLE
Implement Microsoft Graph SDK

### ISSUE THREAD

**Issue by urmade** [microsoft-campus-community/MCC-App_Event-Engine#2]
# Description
In order to create and read events Microsoft Graph has to be used. 
Requirement: Abstract the service principals clientId, clientSecret and scope. This enables using a service principal with delegated permissions locally and swapping it for the MCC global admin service principal in production.

**Comment by MalteRei** [comment]
@Urmade ich fange mal mit diesem Task an. Wenn du der Meinung bist ein anderer Task ist besser zum Anfangen kannst du gerne widersprechen.

**Comment by MalteRei** [comment]
447c1dc4723319b674df51f061c683079443823b implements this functionality. The configuration in development is loaded from local.settings.json (this file is in gitignore because you should not commit your credentials) and in production the application will load the configuration from app settings.
The required configuration is a section under values in the json file with the following attributes:
```
"Values": {
    [other values]
    "Graph:TenantId": "[tenantId from azure under AAD when registering a new application]",
    "Graph:ClientId": "[clientId from azure under AAD when registering a new application]",
    "Graph:AdminPrincipalUsername": "[username/email of a campus-community user]",
    "Graph:AdminPrincipalPassword": "[password for the user]"
}
``´
